### ISSUE TITLE
Figure doesn't update (with tk backend)

### ISSUE THREAD

**Issue by dmcdougall** [dmcdougall/strata-mpl-tutorial#3]
@mdboom I assume you're going to use the tk backend for the demonstration.  The first example showing how to change the defaults doesn't automatically update the figure unless I issue a `plt.draw()` command.  Does yours automatically update?

**Comment by mdboom** [comment]
Hmm...  I can't reproduce, but maybe we should add the `draw` in there just in case for those playing along.  I may not have time to do that until getting to NYC on Monday, however, so feel free if you get to it first.

**Comment by dmcdougall** [comment]
Ok cool.  Thanks for digging.  I'll add them tomorrow.

**Comment by dmcdougall** [comment]
What output do you get from `plt.isinteractive()`?

**Comment by dmcdougall** [comment]
Bear in mind the mpl defaults are used now instead of what is in your `matplotlibrc`, so I wonder if you can recreate the problem now.
